set(PMTRACER_HEADERS
	include/Ray.h
	include/Random.h
	include/Vector2.h
	include/Vector3.h
	include/RGBColor.h
	include/Geometry.h
	include/Plane.h
	include/Sphere.h
	include/Rectangle.h
	include/World.h
	include/Tracer.h
	include/RayCast.h
	include/Whitted.h
	include/AreaLighting.h
	include/PathTrace.h
	include/GlobalTrace.h
	include/Sampler.h
	include/SamplerState.h
	include/Regular.h
	include/PureRandom.h
	include/Jittered.h
	include/MultiJittered.h
	include/NRooks.h
	include/Hammersley.h
	include/Halton.h
	include/ViewPlane.h
	include/Camera.h
	include/Ortographic.h
	include/PinHole.h
	include/ShadeRecord.h
	include/Material.h
	include/BRDF.h
	include/Matte.h
	include/Phong.h
	include/Lambertian.h
	include/Reflective.h
	include/PerfectSpecular.h
	include/GlossySpecular.h
	include/Emissive.h
	include/AmbientOccluder.h
	include/Light.h
	include/Directional.h
	include/PointLight.h
	include/Ambient.h
	include/AreaLight.h
	include/EnvironmentLight.h
)
