set(PMTRACER_SOURCES
	src/Random.cpp
	src/Plane.cpp
	src/Sphere.cpp
	src/Rectangle.cpp
	src/World.cpp
	src/RayCast.cpp
	src/Whitted.cpp
	src/AreaLighting.cpp
	src/PathTrace.cpp
	src/GlobalTrace.cpp
	src/Sampler.cpp
	src/SamplerState.cpp
	src/Regular.cpp
	src/PureRandom.cpp
	src/Jittered.cpp
	src/MultiJittered.cpp
	src/NRooks.cpp
	src/Hammersley.cpp
	src/Halton.cpp
	src/Camera.cpp
	src/Ortographic.cpp
	src/PinHole.cpp
	src/BRDF.cpp
	src/Matte.cpp
	src/Phong.cpp
	src/Reflective.cpp
	src/Emissive.cpp
	src/AmbientOccluder.cpp
	src/AreaLight.cpp
	src/EnvironmentLight.cpp
)
